# Generated by Django 2.2.7 on 2019-11-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comments', verbose_name='Картинка отзыва большая 400 х 340 px')),
                ('writtenBy', models.CharField(default='', max_length=75, verbose_name='От кого отзыв')),
                ('description', models.TextField(verbose_name='Текст отзыва (примерно 380 слов)')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
