# Generated by Django 2.2.7 on 2019-12-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191205_1910'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='pages.ServiceName', verbose_name='Отзыв к услуге'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='comments', verbose_name='Картинка отзыва большая 750 х 390 px'),
        ),
    ]
