# Generated by Django 2.2.7 on 2019-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20191205_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writtenByAvatar',
            field=models.ImageField(null=True, upload_to='comments', verbose_name='Аватарка кто оставил отзыв'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writtenByVk',
            field=models.CharField(max_length=75, null=True, verbose_name='Ссылка на ВК'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(null=True, verbose_name='Текст отзыва (примерно 380 слов)'),
        ),
    ]
