# Generated by Django 2.2.7 on 2019-12-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20191227_0922'),
        ('comments', '0004_auto_20191209_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='service',
            field=models.ManyToManyField(to='pages.ServiceName', verbose_name='Отзыв к услуге'),
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ManyToManyField(blank=True, null=True, to='pages.ServiceName', verbose_name='Отзыв к услуге')),
            ],
            options={
                'verbose_name': 'Видео отзыв',
                'verbose_name_plural': 'Видео отзывы',
            },
        ),
    ]
