# Generated by Django 2.2.7 on 2019-12-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20191227_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='service',
            field=models.ManyToManyField(to='pages.ServiceName', verbose_name='Отзыв к услуге'),
        ),
    ]
