# Generated by Django 2.2.7 on 2019-12-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20191227_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='url',
            field=models.CharField(max_length=75, null=True, verbose_name='youtube-video-id'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='service',
            field=models.ManyToManyField(to='pages.ServiceName', verbose_name='Видео отзыв к услуге'),
        ),
    ]
