# Generated by Django 2.2.6 on 2019-11-18 06:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на страницу с услугой'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
    ]
