# Generated by Django 2.2.6 on 2019-11-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191118_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicename',
            name='page_h1',
            field=models.CharField(max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='page_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
    ]
