# Generated by Django 2.2.6 on 2019-11-19 07:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191119_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicename',
            name='description',
        ),
        migrations.AddField(
            model_name='servicename',
            name='bottomText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Нижний текст на страницу с услугой'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='pageTable',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Таблица (прайс-лист)'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='topText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Верхний текст на страницу с услугой'),
        ),
    ]
