# Generated by Django 2.2.7 on 2019-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_servicename_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для главной')),
                ('indexDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для главной')),
                ('indexKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для главной')),
                ('servicesTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми услугами')),
                ('servicesDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми услугам')),
                ('servicesKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми услугам')),
                ('postsTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми статьями')),
                ('postsDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми статьями')),
                ('postsKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми статьями')),
                ('aboutTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы о компании')),
                ('aboutDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы о компании')),
                ('aboutKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы о компании')),
            ],
        ),
        migrations.AddField(
            model_name='servicename',
            name='image',
            field=models.ImageField(blank=True, upload_to='services_img/', verbose_name='Изображение превью (360 x 250)'),
        ),
    ]
