# Generated by Django 2.2.7 on 2019-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20191119_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seotag',
            options={'verbose_name': 'Теги для статических страниц', 'verbose_name_plural': 'Теги для статических страниц'},
        ),
        migrations.AlterField(
            model_name='servicename',
            name='image',
            field=models.ImageField(null=True, upload_to='services_img/', verbose_name='Изображение превью (360 x 250)'),
        ),
    ]
