# Generated by Django 2.2.7 on 2019-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191205_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='isAtHome',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной?'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='image',
            field=models.ImageField(null=True, upload_to='services_img/', verbose_name='Изображение превью (555 x 225)'),
        ),
    ]
