# Generated by Django 2.2.7 on 2019-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191205_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='services_img/', verbose_name='Изображение для главной превью (170 x 170)'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='image',
            field=models.ImageField(null=True, upload_to='services_img/', verbose_name='Изображение для страницы со всеми услугами (555 x 225)'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
    ]
