# Generated by Django 2.2.7 on 2019-12-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20191205_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='isInCalc',
            field=models.BooleanField(default=False, verbose_name='Отображать в калькуляторе?'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='price1',
            field=models.IntegerField(default=0, verbose_name='Скидка свыше 50 кв.м.'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='price2',
            field=models.IntegerField(default=0, verbose_name='Скидка свыше 100 кв.м.'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость услуги без скидки'),
        ),
    ]
