# Generated by Django 2.2.7 on 2019-12-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20191218_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название разновидности услуги')),
                ('info', models.CharField(max_length=255, null=True, verbose_name='Описание разновидности услуги')),
                ('price', models.IntegerField(null=True, verbose_name='Стоимость')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ServiceName', verbose_name='Разновидность услуги')),
            ],
            options={
                'verbose_name': 'Pазновидность услуги',
                'verbose_name_plural': 'Pазновидности услуг',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Описание приемущества услуги')),
                ('icon', models.ImageField(null=True, upload_to='services_img/', verbose_name='Иконка')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ServiceName', verbose_name='Приемущества услуги')),
            ],
            options={
                'verbose_name': 'Приемущество услуги',
                'verbose_name_plural': 'Приемущества услуг',
            },
        ),
    ]
