# Generated by Django 2.2.7 on 2019-12-26 19:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_servicefeature_serviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='smallText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на страницу с услугой (отображается вверху страницы) '),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='pageText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на страницу с услугой (отображается внизу страницы) '),
        ),
    ]
