# Generated by Django 2.2.7 on 2019-12-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='icon',
            field=models.ImageField(null=True, upload_to='services_img/', verbose_name='Фото'),
        ),
    ]
