# Generated by Django 2.2.7 on 2020-01-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_servicename_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='image_small',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
