# Generated by Django 2.2.7 on 2020-01-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_serviceimage_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeature',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ServiceName', verbose_name='Приемущества для услуги'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание разновидности услуги'),
        ),
        migrations.CreateModel(
            name='ServiceSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Описание этапа работ')),
                ('icon', models.ImageField(null=True, upload_to='services_img/', verbose_name='Иконка')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ServiceName', verbose_name='Этапы работ для услуги')),
            ],
            options={
                'verbose_name': 'Этап работ',
                'verbose_name_plural': 'Этапы работ',
            },
        ),
    ]
