# Generated by Django 2.2.7 on 2020-04-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200115_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotag',
            name='postsDescription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми статьями'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='postsKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми статьями'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='postsTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми статьями'),
        ),
    ]
