# Generated by Django 2.2.7 on 2020-09-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20200415_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='show_calc',
            field=models.BooleanField(default=True, verbose_name='Отображать калькулятор на странице'),
        ),
    ]
