# Generated by Django 2.2.7 on 2020-09-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_servicename_show_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='image_inner',
            field=models.ImageField(blank=True, null=True, upload_to='services_img/', verbose_name='Изображение для блока о нас'),
        ),
    ]
