# Generated by Django 2.2.7 on 2020-10-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_servicename_image_inner'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для блока о нас'),
        ),
    ]
