# Generated by Django 2.2.6 on 2019-11-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1'),
        ),
    ]
