# Generated by Django 2.2.6 on 2019-11-19 07:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_page_h1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='page_description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='page_h1',
            field=models.CharField(max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='page_keywords',
            field=models.TextField(null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='page_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
    ]
