# Generated by Django 2.2.7 on 2020-04-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191119_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
    ]
