# Generated by Django 2.2.7 on 2019-11-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='Нет данных', max_length=255, verbose_name='Имя')),
                ('userPhone', models.CharField(default='Нет данных', max_length=255, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Форма заказа звонка',
                'verbose_name_plural': 'Формы заказа звонка',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(blank=True, default='Нет ответа', max_length=255, verbose_name='Обслуживались ли Вы ранее у сторонней бухгалтерии?')),
                ('question2', models.CharField(blank=True, default='Нет ответа', max_length=255, verbose_name='Количество штатных единиц?')),
                ('question3', models.CharField(blank=True, default='Нет ответа', max_length=255, verbose_name='Количество операций ?')),
                ('question4', models.CharField(blank=True, default='Нет ответа', max_length=255, verbose_name='Система налогообложения?')),
                ('question5', models.CharField(blank=True, default='Нет ответа', max_length=255, verbose_name='Количество контрагентов?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
                ('is_done', models.BooleanField(default=False, verbose_name='Форма обработана? ')),
            ],
            options={
                'verbose_name': 'Квиз форма',
                'verbose_name_plural': 'Квиз формы',
            },
        ),
    ]
