# Generated by Django 2.2.7 on 2019-12-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0003_auto_20191111_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AddField(
            model_name='callbackorder',
            name='service',
            field=models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='callbackorder',
            name='square',
            field=models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Площадь'),
        ),
    ]
